version: 2.1

orbs:
  docker: circleci/docker@1.4.0

jobs:
  build:
    docker: 
      - image: circleci/node:latest
        
    steps:
      - checkout
      - docker/check:
        docker-username: yongwon0824
        docker-password: $DOCKER_PW
      - run: echo "SUCCESS"
  
workflows:
  version: 2.1
  build:
    jobs:
      - build
