version: 2.1

jobs:

  nest-build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: npm i -g @nestjs/cli
      - run : yarn
      - run: ls
      - run: yarn run build
      - run: echo "BUILD SUCCESS"
      - run: ls
  docker-build-and-push:
    executor: docker/docker
        
    steps:
      - setup_remote_docker
      - checkout
      - run: ls
      - docker/check
      - docker/build:
          image: yongwon0824/test
      - docker/push:
          image: yongwon0824/test
      - run: echo "SUCCESS"
  
orbs:
  docker: circleci/docker@1.6.0
  
workflows:
  version: 2.1
  build:
    jobs:
      - nest-build
      - docker-build-and-push:
          requires:
            - nest-build
          context:
            - DOCKER
