version: 2.1

orbs:
  docker: circleci/docker@1.6.0

jobs:
  build:
    docker: 
      - image: circleci/node:latest
        
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_ID/test
      - docker/push:
          image: $DOCKER_ID/test
      - run: echo "SUCCESS"
  
workflows:
  version: 2.1
  build:
    jobs:
      - build:
          context:
            - DOCKER
