version: 2
jobs:
  push:
    executor : docker/docker
    steps:
      - checkout
      - run: 
        command: |
          docker login
      - run:
        command: |
          echo "Digest is: $(</tmp/digest.txt)"
          echo "testing!!!"
  
workflows:
  version: 2
  one_and_two:
    jobs:
      - push
      - two:
          requires:
            - push