version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:latest
        auth:
          username: yongwon0824 
          password: $DOCKER_PW
    steps:
      - checkout
      - run: echo $DOCKER_PW
  
workflows:
  version: 2.1
  build:
    jobs:
      - build
