version: 2.1

jobs:

  nest-build:
    docker:
      - image: node:latest
    working_directory: ~/vidalog
    steps:
      - checkout
      - run: npm i -g @nestjs/cli
      - run : yarn
      - run: pwd
      - run: yarn run build
      - run: echo "BUILD SUCCESS"
      - run: ls
      - persist_to_workspace:
          root: ~/vidalog
          paths:
            - dist/*
            - node_modules/*
  docker-build-and-push:
    executor: docker/docker
    working_directory: ~/vidalog
    steps:
      - setup_remote_docker:
        version: 20.10.7
      - checkout
      - attach_workspace:
          at: ~/vidalog
      - run: ls
      - run: pwd
      - run: ls
      - docker/check
      - docker/build:
          image: yongwon0824/test
      - docker/push:
          image: yongwon0824/test
      - run: echo "SUCCESS"
      
  
orbs:
  docker: circleci/docker@1.6.0
  
workflows:
  version: 2.1
  build:
    jobs:
      - nest-build
      - docker-build-and-push:
          requires:
            - nest-build
          context:
            - DOCKER
